# Generated by Django 3.1.7 on 2021-11-12 16:13

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='body',
            field=tinymce.models.HTMLField(default='Nothing', verbose_name='Body'),
        ),
    ]
