# Generated by Django 3.1.7 on 2021-11-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_idea_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='type',
            field=models.CharField(choices=[('idea', 'ایده'), ('offer', 'پیشنهاد'), ('comment', 'انتقاد')], default='idea', max_length=7),
        ),
    ]
