# Generated by Django 3.1.7 on 2021-11-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_auto_20211121_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='type',
            field=models.CharField(choices=[('ایده', 'idea'), ('پیشنهاد', 'offer'), ('انتقاد', 'comment')], default='idea', max_length=7),
        ),
    ]
