# Generated by Django 3.1.7 on 2021-11-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0006_auto_20211125_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
