# Generated by Django 3.1.7 on 2021-12-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0009_auto_20211125_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='respond',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
